default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ruby_capstone_module_1_development

test:
  <<: *default
  database: ruby_capstone_module_1_test

production:
